### ISSUE TITLE
File rotation issue

### ISSUE THREAD

**Issue by fmonjalet** [quarkslab/irma-frontend#105]
Hi,

We would like to set up a file rotation system for the frontend's `/var/irma/samples`. I have tried to remove some samples, but if I scan them again later (I force the scan to be performed with the REST API), celery and uwsgi raise an ftp upload error caused by an `IOError` (`file not found`). I guess that IRMA does not handle cases where samples have been deleted and should be put again in `/var/irma/samples` to be rescanned.

Would it be possible to fix this issue? If not, is there any recommended way to safely rotate files in `/var/irma/samples` to avoid disk saturation?

Thanks!

Florent

**EDIT:** The bug appears in IRMA 1.2.0, but the diffs with 1.3.0 do not seem to fix it, is it reproducible on your setup?

**Comment by ch0k0bn** [comment]
There is a specific periodic task to remove file from FS (https://github.com/quarkslab/irma-frontend/blob/master/frontend/tasks.py#L68), its meant to be executed by celerybeat. But if you want to manually do it, you have to call https://github.com/quarkslab/irma-frontend/blob/master/frontend/controllers/filectrl.py#L21 because path field should be set to None.
One more missing doc. Will put this in the FAQ section of the doc.

**Comment by fmonjalet** [comment]
Thanks for the pointers, I missed these ones. I think it will do the job for us. I'll try that and keep you in touch, the issue can be closed for me (I'll reopen if necessary).

**Comment by guillaumededrie** [comment]
You're rigth @fmonjalet, I just opened an issue related to your tip: https://github.com/quarkslab/irma-frontend/issues/106.
Regards.
